name: prometheus-node-exporter

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull & Push to AWS ECR Private
        uses: opspresso/action-docker@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRUCE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRUCE }}
          AWS_REGION: "ap-northeast-2"
          BASE_IMAGE: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
          IMAGE_NAME: mirror/aws/aws-ebs-csi-driver
          TAG_NAME: "v1.5.0"
          PLATFORM: "linux/amd64,linux/arm64"
          BUILDX: "true"
