name: mirror

on:
  repository_dispatch:
    types:
      - mirror

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull & Push to AWS ECR Private
        uses: opspresso/action-docker@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRUCE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRUCE }}
          AWS_REGION: "ap-northeast-2"
          BASE_IMAGE: ${{ github.event.client_payload.base_image }}
          IMAGE_NAME: ${{ github.event.client_payload.image_name }}
          TAG_NAME: ${{ github.event.client_payload.tag_name }}
          PLATFORM: ${{ github.event.client_payload.platform }}
          BUILDX: ${{ github.event.client_payload.buildx }}
