name: mirror

on:
  repository_dispatch:
    types:
      - mirror

env:
  AWS_REGION: "ap-northeast-2"
  AWS_ROLE_ARN: "arn:aws:iam::396608815058:role/image-mirror"

  BASE_IMAGE: ${{ github.event.client_payload.base_image }}
  IMAGE_NAME: ${{ github.event.client_payload.image_name }}
  TAG_NAME: ${{ github.event.client_payload.tag_name }}
  PLATFORM: ${{ github.event.client_payload.platform }}
  BUILDX: ${{ github.event.client_payload.buildx }}

  REPOSITORY: "396608815058.dkr.ecr.ap-northeast-2.amazonaws.com"

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: github-actions-ci-bot
          aws-region: ${{ env.AWS_REGION }}

      - name: Push image to AWS ECR
        run: |
          docker buildx imagetools create \
            --tag ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} \
            ${{ env.BASE_IMAGE }}:${{ env.TAG_NAME }}
