name: prometheus-node-exporter

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Build
        run: |
          mkdir -p ./target
          echo "v1.3.1" > ./target/TAG_NAME

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BASE_IMAGE: quay.io/prometheus/node-exporter
          IMAGE_NAME: prometheus-node-exporter
          PLATFORM: "linux/amd64,linux/arm64"
          BUILDX: "true"

      - name: Pull & Push to AWS ECR Private
        uses: opspresso/action-docker@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRUCE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRUCE }}
          AWS_REGION: "ap-northeast-2"
          BASE_IMAGE: quay.io/prometheus/node-exporter
          IMAGE_NAME: quay.io/prometheus/node-exporter
          PLATFORM: "linux/amd64,linux/arm64"
          BUILDX: "true"
